# Generated by Django 5.0.4 on 2024-04-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
