# Generated by Django 5.0.4 on 2024-04-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_article_image_alter_article_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
