# Generated by Django 5.0.4 on 2024-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/media/images/placeholder.jpg', upload_to='images'),
        ),
    ]
